sudo: required

language: ruby

rvm:
 - "1.9.3"

before_install:
  - >
    sudo add-apt-repository -y ppa:fkrull/deadsnakes \
        && sudo apt-get update -qq \
        && sudo apt-get install -yqq python3.4
  - wget https://bootstrap.pypa.io/get-pip.py && python3.4 get-pip.py --user; rm -f get-pip.py

install:
  - cd ${TRAVIS_BUILD_DIR}/dashboard && bundle install --deployment --jobs 4 --retry 3
  - cd ${TRAVIS_BUILD_DIR}/dashboard && npm install
  - cd ${TRAVIS_BUILD_DIR}/qatserver && pip install --user -r requirements.txt
cache:
  directories:
    - dashboard/vendor/bundle
    - dashboard/node_modules
    - ${HOME}/.cache/pip

script:
  - cd ${TRAVIS_BUILD_DIR}/dashboard && bundle exec rake
  - cd ${TRAVIS_BUILD_DIR}/dashboard && npm run test
  - cd ${TRAVIS_BUILD_DIR}/qatserver && python3.4 -m pytest -v

