language: ruby
rvm:
 - "1.9.3"
 - rbx
install:
  - cd ${TRAVIS_BUILD_DIR}/dashboard && bundle install
  - cd ${TRAVIS_BUILD_DIR}/dashboard && npm install
script:
  - cd ${TRAVIS_BUILD_DIR}/dashboard && bundle exec rake
  - cd ${TRAVIS_BUILD_DIR}/dashboard && npm run test
